<?php

use Magento\Framework\App\ObjectManager;
use Magento\Store\Model\ScopeInterface;

$objectManager = ObjectManager::getInstance();
$scopeConfig = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface');
$helper = $objectManager->get(\Mageseller\SupplierImport\Helper\Xit::class);
$isEnableEdsModule = $helper->getEnable();
$productFeedUrl = $scopeConfig->getValue('eds/general/eds_feed_url', ScopeInterface::SCOPE_STORE);
$newProductFeedUrl = $scopeConfig->getValue('eds/general/eds_new_feed_url', ScopeInterface::SCOPE_STORE);
if ($isEnableEdsModule) {
    ?>

    <div class="Category-Map">


    </div>
    <table class="Category-Map-Table">
        <tr>
            <td><label style="float: left;">Supplier Category</label></td>
            <td><label style="float: left;">Shop Category</label></td>
            <!-- <td><label style="float: left;">Sort Order</label></td> -->
            <td>Action</td>
        </tr>
        <tr>
            <td><input type="text" name="supplier-input" id="supplier-input" value=""></td>
            <td><input type="text" name="shop-input" id="shop-input" value="">
                <input type="hidden" name="shop-input1" id="shop-input1" value=""></td>
            <!-- <td><input type="text" name="sort-order" id="sort-order" value="0"></td> -->
            <td>
                <button name="submit" id="submit" value="Submit" class="action- scalable primary"> Submit</button>
            </td>
        </tr>
    </table>
    <?php
    $supplierCategories = $objectManager->create('\Mageseller\SupplierImport\Model\XitCategoryFactory')->create()->getCollection();
    $categoryArray = $supplierCategories->getColumnValues('name');
    $categories = $objectManager->create('Magento\Catalog\Model\ResourceModel\Category\CollectionFactory')->create()
        ->addAttributeToSelect('*');
    $categoryNameArray = [];

    foreach ($categories as $category) {
        $mappedCategories = explode(",", $category->getData('xit_category_ids'));
        foreach ($mappedCategories as $mapCategory) {
            if ($mapCategory) {
                $categoryNameArray[] = $mapCategory;
                $categoryMapArray[$mapCategory] = $category->getName();
            }
        }
    } ?>
    <div style="display: flex;">
        <div class="supplier-category left tree" id="tree">
            <h3>Supplier category</h1>
                <div class="supplier-category-body tree">
                    <ul>
                        <?php foreach ($categoryArray as $category): ?>
                            <li>
                                <a href="javascript:void(0)" <?php if (in_array($category, $categoryNameArray)) {
                                    echo "style=color:green";
                                } ?>><?php echo $category; ?></a><?php if (in_array($category, $categoryNameArray)) {
                                    echo " ===> " . $categoryMapArray[$category];
                                } ?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
        </div>
        <div class="shop-category right">
            <h3>Shop category</h1>
                <div class="shop-category-body tree" id="tree"><?php echo $helper->getCategories(1); ?></div>
        </div>
    </div>


    <?php
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $baseUrl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
        ->getStore($storeManager->getStore()->getId())
        ->getBaseUrl();
    $saveCategoryUrl = $baseUrl . "mageseller_supplierimport/xitcategory/savecategory";
    $supplierCategoryUrl = $baseUrl . "mageseller_supplierimport/xitcategory/suppliercategory";
    $delCategoryUrl = $baseUrl . "mageseller_supplierimport/xitcategory/delcategory"; ?>
    <script type="text/javascript">
        require(['jquery', 'jquery/ui'], function ($) {
            $(document).ready(function () {
                $('.supplier-category').find("li a").live('click', function () {
                    $("#supplier-input").val($(this).html());
                });

                $('.shop-category-body').find("li .shop-category-li").live('click', function () {
                    $("#shop-input").val($(this).html());
                    $("#shop-input1").val($(this).attr("data"));
                });

                $('#submit').live('click', function () {
                    var url = '<?php echo $saveCategoryUrl; ?>';
                    var supplier = $("#supplier-input").val();
                    var shop = $("#shop-input").val();
                    var shopId = $("#shop-input1").val();
                    var flag = 1;
                    var alreadyMappedArray = <?php echo json_encode($categoryNameArray); ?>;
                    for (var i = 0; i < alreadyMappedArray.length; i++) {
                        if (alreadyMappedArray[i] == supplier) {
                            flag = 2;
                        }
                    }


                    if (flag == 2) {
                        $("#shop-input").val("");
                        $("#shop-input1").val("");
                        $("#supplier-input").val("");
                        alert(supplier + " is already mapped");

                    } else {
                        if (supplier && shop) {
                            $.ajax({
                                url: url,
                                data: {"supplier": supplier, "shop": shop, "sortorder": 0, "shopId": shopId},
                                type: "POST",
                                showLoader: true,
                                success: function (response) {
                                    $('.shop-category-body').html(response);
                                    $.ajax({
                                        url: '<?php echo $supplierCategoryUrl; ?>',
                                        data: {"supplier": supplier, "shop": shop, "sortorder": 0, "shopId": shopId},
                                        type: "POST",
                                        showLoader: true,
                                        success: function (response) {
                                            $('.supplier-category-body').html(response);
                                            $("#shop-input").val("");
                                            $("#shop-input1").val("");
                                            $("#supplier-input").val("");
                                            //window.location.reload();
                                        }
                                    });
                                }
                            });
                        }
                    }
                });
                $('.remove-shop-category').live('click', function () {
                    var url = '<?php echo $delCategoryUrl; ?>';
                    var shopId = $(this).attr("data");
                    if (shopId) {
                        $.ajax({
                            url: url,
                            data: {"shopId": shopId},
                            type: "POST",
                            showLoader: true,
                            success: function (response) {
                                $('.shop-category-body').html(response);
                                //window.location.reload();
                                $.ajax({
                                    url: '<?php echo $supplierCategoryUrl; ?>',
                                    data: {"shopId": shopId},
                                    type: "POST",
                                    showLoader: true,
                                    success: function (response) {
                                        $('.supplier-category-body').html(response);
                                        //window.location.reload();
                                    }
                                });
                            }
                        });

                    }
                });
            });
        });

    </script>
    <?php
} else {
    ?>
    <p>Please Enable Module to Map Category.</p>
    <?php
}
?>
<style type="text/css">
    .supplier-category {
        width: 50%;
        float: left;
    }

    .shop-category {
        width: 50%;
        float: right;
    }

    .Category-Map-Table td {
        padding-right: 20px;
    }

    .Category-Map-Table {
        margin-bottom: 20px;
    }

    ul {
        padding-left: 20px !important;
    }

    .tree, .tree ul {
        list-style-type: none;
        background: url(vline.png) repeat-y;
        margin: 0;
        padding: 0;
    }

    .tree ul {
        margin-left: 10px;
    }

    .tree li {
        margin: 0;
        padding: 0 12px;
        line-height: 20px;
        background: url(node.png) no-repeat;
        color: #369;
        font-weight: bold;
    }

    .tree li.last {
        background: #fff url(lastnode.png) no-repeat;
    }

    .supplier-category-body.tree {
        overflow: scroll;
        height: 87vh;
    }

    .shop-category-body.tree {
        overflow: scroll;
        height: 87vh;
    }
</style>
