<?php
/** @var \Mageseller\LeadersystemsImport\Block\Adminhtml\Category $block */
$helper = $this->helper(\Mageseller\LeadersystemsImport\Helper\Leadersystems::class);
$isEnableEdsModule = $helper->getEnable();
?>
<?php if ($isEnableEdsModule) : ?>
    <?php
        $categoryMapArray = $helper->getMappedCategory();
        $supplierCategories = $helper->getSupplierCategory();
        $categoryNameArray = $supplierCategories->getColumnValues('name');
    ?>
    <table class="Category-Map-Table">
        <tr>
            <td><label style="float: left;">Supplier Category</label></td>
            <td><label style="float: left;">Magento Category</label></td>
            <td>Action</td>
        </tr>
        <tr>
            <td>
                <input type="text" name="supplier_input" id="supplier_input" value="">
                <input type="hidden" name="supplier_input_id" id="supplier_input_id" value="">
            </td>
            <td>
                <input type="text" name="shop_input" id="shop_input" value="">
                <input type="hidden" name="shop_input_id" id="shop_input_id" value="">
            </td>
            <td>
                <button name="submit" id="submit" value="Submit" class="action- scalable primary"> Submit</button>
            </td>
        </tr>
    </table>
    <div style="display: flex;">
        <div class="supplier-category left tree" id="tree">
            <h1>Supplier category</h1>
            <div class="supplier-category-body tree">
                <ul>
                    <?= $helper->getSupplierCategoryData()?>
                </ul>
            </div>
        </div>
        <div class="shop-category right">
            <h1>Magento category</h1>
            <div class="shop-category-body tree" id="tree"><?php echo $helper->getCategories(1); ?></div>
        </div>
    </div>
    <?php
    $formData = [];
    $formData['save_category_url'] = $this->getUrl("mageseller_leadersystemsimport/leadersystemscategory/savecategory");
    $formData['delete_category_url'] = $this->getUrl("mageseller_leadersystemsimport/leadersystemscategory/delcategory");
    $formData['supplier_category_url'] = $this->getUrl("mageseller_leadersystemsimport/leadersystemscategory/suppliercategory");
    $formData['already_mapped_array'] = json_encode($categoryNameArray);
    $serializedFormData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($formData); ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Mageseller_LeadersystemsImport/js/categorymap": <?php /* @noEscape */
        echo $serializedFormData; ?>
            }
        }
    </script>
<?php else: ?>
    <p>Please Enable Module to Map Category.</p>
<?php endif; ?>